models/alert.py
import uuid
from typing import Dict
from dataclasses import dataclass, field

from models import Model, Item, User
from libs.emails.mailgun import Mailgun

@dataclass(eq=False)
class Alert(Model):
    collection: str = field(init=False, default="alerts")
    name: str
    item_id: str
    price_limit: float
    user_email: str
    _id: str = field(default_factory=lambda: uuid.uuid4().hex)

    def __post_init__(self):
        self.item = Item.get_by_id(self.item_id)
        self.user = User.find_by_email(self.user_email)

    def json(self) -> Dict:
        return {
            "_id": self._id,
            "name": self.name,
            "item_id": self.item_id,
            "price_limit": self.price_limit,
            "user_email": self.user_email
        }

    def load_item_price(self) -> float:
        self.item.load_price()
        return self.item.price

    def notify_if_price_reached(self) -> None:
        if self.item.price <= self.price_limit:
            print(f"Item {self.item} has reached a price under {self.price_limit}. Latest price: {self.item.price}")

            Mailgun.send_email(
                receivers=[self.user_email],
                subject=f"Notification for {self.name}",
                text=f"Your alert {self.name} has reached a price under {self.price_limit}. The latest price is {self.item.price}. Go to this address to check your item: {self.item.url}.",
            )

controllers/alerts.py
from flask import Blueprint, request, render_template, url_for, redirect, session, flash
from models.alert import Alert
from models.item import Item
from models.store import Store
from common.decorators import require_login

from common.errors import Error

alert_blueprint = Blueprint("alert_blueprint", __name__)


@alert_blueprint.route("/", methods=['GET'])
@require_login
def index():
    alerts = Alert.find_many_by("user_email", session['email'])
    return render_template("alerts/index.html", alerts=alerts)


@alert_blueprint.route("/new", methods=["GET", 'POST'])
@require_login
def create_alert():
    if request.method == "POST":
        alert_name = request.form["alert_name"]
        item_url = request.form["item_url"]
        price_limit = float(request.form["price_limit"])

        try:
            store = Store.find_by_url(item_url)
            item = Item(item_url, store.tag_name, store.query)
            item.load_price()
            item.save_to_mongo()
            Alert(alert_name, item._id, price_limit, session["email"]).save_to_mongo()
            flash("success", 'success')
        except Error as e:
            flash(e, 'danger')

    stores = Store.all()
    return render_template("alerts/new_alert.html", stores=stores)


@alert_blueprint.route("/edit/<string:alert_id>", methods=["GET", "POST"])
@require_login
def edit_alert(alert_id):
    alert = Alert.get_by_id(alert_id)

    if request.method == "POST":
        price_limit = float(request.form["price_limit"])

        alert.price_limit = price_limit
        alert.save_to_mongo()
        flash("success", 'success')
        # return redirect(url_for('.index'))

    return render_template("alerts/edit_alert.html", alert=alert)


@alert_blueprint.route("/delete/<string:alert_id>")
@require_login
def delete_alert(alert_id):
    alert = Alert.get_by_id(alert_id)
    if alert.user_email == session["email"]:
        alert.remove_from_mongo()
    return redirect(url_for(".index"))

templates/alerts/edit_alert.html
{% extends "base.html" %}
{% block content %}
<header><h1>Edit Alert</h1></header>

<section class="edit-item-form">
<form method="post">
    <div class="mb-3">
        <label for="alert_name" class="form-label">Alert Name</label>
        <input type="text" class="form-control" id="alert_name" name="alert_name" value="{{ alert.name }}" disabled/>
    </div>
    <div class="mb-3">
        <label for="item_url" class="form-label">Item URL</label>
        <input type="text" class="form-control" id="item_url" name="item_url" value="{{ alert.item.url }}" disabled/>
    </div>
    <div class="mb-3">
        <label for="price_limit" class="form-label">Price Limit</label>
        <input type="text" class="form-control" id="price_limit" name="price_limit" value="{{ alert.price_limit }}" aria-describedby="priceLimitHelp"/>
        <small id="priceLimitHelp" class="form-text">The price limit to trigger alerts</small>
    </div>

    <button type="submit" class="btn btn-primary">Update</button>
</form>

</section>

{% endblock %}

templates/alerts/index.html
{% extends "base.html" %}
{% block content %}
<header class="pb-3">
    <h1>All Alerts</h1>
    <a class="btn btn-primary" href="{{ url_for('alert_blueprint.create_alert') }}" >Create new</a>
</header>
<section>
    <div class="list-group">
        {% for alert in alerts %}
        <div class="list-group-item">
            <h4>Title: {{ alert.name }}</h4>
            <p>Item Id: {{ alert.item_id }}</p>
            <p>Price Limit: {{ alert.price_limit }}</p>
            <a class="btn btn-secondary" href="{{ url_for('alert_blueprint.edit_alert', alert_id=alert._id) }}">Edit</a>

            <a class="btn btn-danger popover-btn" href="{{ url_for('alert_blueprint.delete_alert', alert_id=alert._id) }}">Delete</a>
{#            <div class="card popover-content" style="width: 18rem;">#}
{#                <div class="card-body">#}
{#                    <h3>Are you sure to delete this store?</h3>#}
{#                    <span><a class="btn btn-light ">Cancel</a></span>#}
{#                    <span><a class="btn btn-danger" href="{{ url_for('alert_blueprint.delete_alert', alert_id=alert._id) }}">Confirm</a></span>#}
{#                </div>#}
{#            </div>#}
        </div>
        {% endfor %}
    </div>

</section>
{% endblock %}

templates/alerts/new_alert.html
{% extends "base.html" %}
{% block content %}
<header><h1>Create Alert</h1></header>

<section class="create-item-form">
<form method="post">
    <div class="mb-3">
        <label for="alert_name" class="form-label">Alert Name</label>
        <input type="text" class="form-control" id="alert_name" name="alert_name" placeholder="Airpods" required/>
    </div>
    <div class="mb-3">
        <label for="item_url" class="form-label">Item URL</label>
        <input type="text" class="form-control" id="item_url" name="item_url" placeholder="https://..." required/>
        <small id="itemUrlHelp" class="form-text">You can find item url from</small>
        <small>
            {% for store in stores %}
                <a class="form-link" href="{{ store.url_prefix }}" target="_blank">{{ store.name }}</a>
            {% endfor %}
        </small>
    </div>
    <div class="mb-3">
        <label for="price_limit" class="form-label">Price Limit</label>
        <input type="text" class="form-control" id="price_limit" name="price_limit" placeholder="100" aria-describedby="priceLimitHelp" required/>
        <small id="priceLimitHelp" class="form-text">The price limit to trigger alerts</small>
    </div>

    <button type="submit" class="btn btn-primary">Create</button>
</form>

</section>

{% endblock %}