models/store.py
from dataclasses import dataclass, field
import uuid
import re
from typing import Dict
from models.model import Model

@dataclass(eq=False)
class Store(Model):
    collection: str = field(init=False, default="stores")
    name: str
    url_prefix: str
    tag_name: str
    query: Dict
    _id: str = field(default_factory=lambda: uuid.uuid4().hex)

    def json(self) -> Dict:
        return {
            "_id": self._id,
            "name": self.name,
            "url_prefix": self.url_prefix,
            "tag_name": self.tag_name,
            "query": self.query
        }

    @classmethod
    def get_by_name(cls, store_name) -> "Store":
        return cls.find_one_by("name", store_name)


    @classmethod
    def get_by_url_prefix(cls, url_prefix) -> "Store":
        pattern = "^{}".format(url_prefix)
        url_regex = {"$regex": pattern}
        return cls.find_one_by("url_prefix", url_regex)

    @classmethod
    def find_by_url(cls, url) -> "Store":
        """
        Return a store from a url
        :param url: The item's url
        :return: a store
        """
        pattern = re.compile("(https?://.*?)/")
        url_prefix = pattern.search(url).group(1)

        return cls.get_by_url_prefix(url_prefix)

controllers/stores.py
import json
from flask import Blueprint, render_template, request, redirect, url_for, session, flash
from models.store import Store
from common.decorators import require_login, require_admain


store_blueprint = Blueprint("store_blueprint", __name__)


@store_blueprint.route("/")
@require_login
def index():
    # print(session["email"])
    stores = Store.all()
    return render_template("stores/index.html", stores=stores)


@store_blueprint.route("/new", methods=["GET", "POST"])
@require_admain
def create_store():
    if request.method == "POST":
        name = request.form["name"]
        url_prefix = request.form["url_prefix"]
        tag_name = request.form["tag_name"]
        query = {request.form["attribute"]: request.form["value"]}

        Store(name, url_prefix, tag_name, query).save_to_mongo()
        flash("success", 'success')

    return render_template("stores/new_store.html")


@store_blueprint.route("/edit/<string:store_id>", methods=["GET","POST"])
@require_admain
def edit_store(store_id):
    store = Store.get_by_id(store_id)

    if request.method == "POST":
        store.url_prefix = request.form["url_prefix"]
        store.tag_name = request.form["tag_name"]
        store.query = {request.form["attribute"]: request.form["value"]}

        store.save_to_mongo()
        flash("success", 'success')
        # return redirect(url_for(".index"))

    return render_template("stores/edit_store.html", store=store)


@store_blueprint.route("delete/<string:store_id>")
@require_admain
def delete_store(store_id):
    Store.get_by_id(store_id).remove_from_mongo()
    return redirect(url_for(".index"))

templates/stores/edit_store.html
{% extends "base.html" %}
{% block content %}
<header><h1>Edit Store</h1></header>

<section class="edit-item-form">
<form method="post">
    <div class="mb-3">
        <label for="name" class="form-label">Name</label>
        <input type="text" class="form-control" id="name" name="name" value="{{ store.name }}" />
    </div>
    <div class="mb-3">
        <label for="url_prefix" class="form-label">URL Prefix</label>
        <input type="text" class="form-control" id="url_prefix" name="url_prefix" value="{{ store.url_prefix }} "/>
    </div>
    <div class="mb-3">
        <label for="tag_name" class="form-label">Tag Name</label>
        <input type="text" class="form-control" id="tag_name" name="tag_name" value="{{ store.tag_name }}" aria-describedby="tagNameHelp"/>
        <small id="priceLimitHelp" class="form-text">The HTML element to find the product price</small>
    </div>

    <div class="mb-3">
        <label for="query" class="form-label">Query</label>
        {% for attribute, value in store.query.items() %}
            <input type="text" class="form-control mb-1" id="attribute" name="attribute" value='{{ attribute }}' />
            <input type="text" class="form-control mb-1" id="value" name="value" value='{{ value }}' />

        {% endfor %}
{#        <input type="text" class="form-control" id="query" name="query" value='{{ store.query }}' />#}

    </div>

    <button type="submit" class="btn btn-primary">Update</button>
</form>

</section>

{% endblock %}

templates/stores/index.html
{% extends "base.html" %}
{% block content %}
<header class="pb-3">
    <h1>All Stores</h1>
    {% if session["email"] == config.ADMIN %}
        <a class="btn btn-primary" href="{{ url_for('store_blueprint.create_store') }}">Create</a>
    {% endif %}
</header>
<section>
    <div class="row">
        {% for store in stores %}
        <div class="col-sm-4 mb-3">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">{{ store.name }}</h4>
                    <div class="card-text">
        {#                <p>URL Prefix: {{ store.url_prefix }}</p>#}
                        <p>Tag Name: {{ store.tag_name }}</p>
                        <p>Query: {{ store.query }}</p>
                        <a class="btn btn-info mb-2" href="{{ store.url_prefix }}" target="_blank"> Go to website</a>
                        <div>
                        {% if session["email"] == config.ADMIN %}
                            <a class="btn btn-secondary" href="{{ url_for('store_blueprint.edit_store', store_id=store._id) }}">Edit</a>
                            <a class="btn btn-danger" href="{{ url_for('store_blueprint.delete_store', store_id=store._id) }}">Delete</a>
                        {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>




</section>
{% endblock %}

templates/stores/new_store.html
{% extends "base.html" %}
{% block content %}
<header><h1>Create Store</h1></header>

<section class="create-item-form">
<form method="post">
    <div class="mb-3">
        <label for="name" class="form-label" >Name</label>
        <input type="text" class="form-control" id="name" name="name" placeholder="Amazon" required/>
    </div>
    <div class="mb-3">
        <label for="url_prefix" class="form-label">URL Prefix</label>
        <input type="text" class="form-control" id="url_prefix" name="url_prefix" placeholder="https://www.amazon.com" required/>
    </div>
    <div class="mb-3">
        <label for="tag_name" class="form-label">Tag Name</label>
        <input type="text" class="form-control" id="tag_name" name="tag_name" placeholder="span" aria-describedby="tagNameHelp" required/>
        <small id="priceLimitHelp" class="form-text">The HTML element to find the product price</small>
    </div>

    <div class="mb-3">
        <label for="query" class="form-label">Query</label>
{#        <input type="text" class="form-control" id="query" name="query" placeholder='{"class": "product-price"}' />#}
        <input type="text" class="form-control mb-1" id="attribute" name="attribute" placeholder="class" required/>
        <input type="text" class="form-control mb-1" id="value" name="value" placeholder="price-num" required/>

    </div>

    <button type="submit" class="btn btn-primary">Create new</button>
</form>

</section>

{% endblock %}