controllers/stores.py
import json
from flask import Blueprint, render_template, request, redirect, url_for, session, flash
from models.store import Store
from common.decorators import require_login, require_admain


store_blueprint = Blueprint("store_blueprint", __name__)


@store_blueprint.route("/")
@require_login
def index():
    # print(session["email"])
    stores = Store.all()
    return render_template("stores/index.html", stores=stores)


@store_blueprint.route("/new", methods=["GET", "POST"])
@require_admain
def create_store():
    if request.method == "POST":
        name = request.form["name"]
        url_prefix = request.form["url_prefix"]
        tag_name = request.form["tag_name"]
        query = {request.form["attribute"]: request.form["value"]}

        Store(name, url_prefix, tag_name, query).save_to_mongo()
        flash("success", 'success')

    return render_template("stores/new_store.html")


@store_blueprint.route("/edit/<string:store_id>", methods=["GET","POST"])
@require_admain
def edit_store(store_id):
    store = Store.get_by_id(store_id)

    if request.method == "POST":
        store.url_prefix = request.form["url_prefix"]
        store.tag_name = request.form["tag_name"]
        store.query = {request.form["attribute"]: request.form["value"]}

        store.save_to_mongo()
        flash("success", 'success')
        # return redirect(url_for(".index"))

    return render_template("stores/edit_store.html", store=store)


@store_blueprint.route("delete/<string:store_id>")
@require_admain
def delete_store(store_id):
    Store.get_by_id(store_id).remove_from_mongo()
    return redirect(url_for(".index"))

controllers/users.py
from flask import Blueprint, request, render_template, redirect, url_for, session, flash

from models import User, Store
from common.errors import Error


user_blueprint = Blueprint("user_blueprint", __name__)


@user_blueprint.route("/register", methods=["GET", "POST"])
def register_user():
    if request.method == "POST":
        email = request.form["email"]
        password = request.form["password"]

        try:
            if User.register_user(email, password):
                session["email"] = email
                return redirect(url_for('.login_user'))
        except Error as e:
            print(e.message)
            flash(e, 'danger')

    return render_template("users/register.html")


@user_blueprint.route("/login", methods=["GET", "POST"])
def login_user():
    if request.method == "POST":
        email = request.form["email"]
        password = request.form["password"]

        try:
            if User.is_login_valid(email, password):
                session["email"] = email
                return redirect(url_for('alert_blueprint.index'))

        except Error as e:
            print(e.message)
            flash(e, 'danger')

    return render_template("users/login.html")


@user_blueprint.route("/logout")
def logout_user():
    session["email"] = None
    flash("You have successfully logged out!", 'success')
    return render_template("users/logout.html")

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Price Alerts</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark p-3 mb-3">
    <a class="navbar-brand" href="/">Price Alert</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
     </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <div class="navbar-nav mr-auto">
                <a class="nav-item nav-link" href="{{ url_for('alert_blueprint.index') }}">Alerts</a>
                <a class="nav-item nav-link" href="{{ url_for('store_blueprint.index') }}">Stores</a>
                <a class="nav-item nav-link" href="{{ url_for('user_blueprint.login_user') }}">Log in</a>
                <a class="nav-item nav-link" href="{{ url_for('user_blueprint.logout_user') }}">Log out</a>
                <a class="nav-item nav-link " href="{{ url_for('user_blueprint.register_user') }}">Create an account</a>
        </div>
    </div>

</nav>
<div class="content container mx-auto mb-5" style="width: 75%">

{% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        {% for category, message in messages %}
            <div class="alert alert-{{ category }}" role="alert">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
{% endwith %}
{% block content %}

{% endblock %}
</div>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script>
$('.carousel').carousel({
  interval: 1500
})
</script>
</body>
</html>

templates/home.html
{% extends "base.html" %}
{% block content %}

<div class="jumbotron">
  <div class="container">
      <div class="d-flex">
          <div>
              <h1 class="display-4">Price Alert</h1>
              <p class="lead">We scan online store websites to alert you of price drops in items that interest you.</p>
              <a class="btn btn-primary btn-lg" href="{{ url_for('user_blueprint.login_user') }}" role="button">Get Started</a>
          </div>

          <div>
              <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                  <ol class="carousel-indicators">
                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>

                  </ol>
                  <div class="carousel-inner">
                      <div class="carousel-item active">
                          <img class="d-block w-100" src="{{ url_for('static', filename='tv-target.png') }}" alt="None">
                      </div>
                      <div class="carousel-item">
                          <img class="d-block w-100" src="{{ url_for('static', filename='boseheadphone.png') }}" alt="First slide">
                      </div>
                      <div class="carousel-item">
                          <img class="d-block w-100" src="{{ url_for('static', filename='macbook.png') }}" alt="Second slide">
                      </div>
                  </div>
                  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" style="color: black" aria-hidden="true"></span>
                    <span class="sr-only text-info">Previous</span>
                  </a>
                  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                  </a>
              </div>

          </div>
      </div>

  </div>
</div>
{% endblock %}